import {
  BadRequestException,
  ForbiddenException,
  NotFoundException,
  HttpVersionNotSupportedException,
  UnsupportedMediaTypeException,
  UnprocessableEntityException,
  ServiceUnavailableException,
  PayloadTooLargeException,
  RequestTimeoutException,
  PreconditionFailedException,
  NotAcceptableException,
  MethodNotAllowedException,
  UnauthorizedException,
  NotImplementedException,
  BadGatewayException,
  GatewayTimeoutException,
  ConflictException,
  GoneException,
  MisdirectedException,
  ImATeapotException,
  HttpException,
} from '@nestjs/common';

export const isNestJsException = (error: any): boolean => {
  const exceptions = [
    BadRequestException,
    NotFoundException,
    ForbiddenException,
    HttpVersionNotSupportedException,
    UnsupportedMediaTypeException,
    UnprocessableEntityException,
    ServiceUnavailableException,
    PayloadTooLargeException,
    RequestTimeoutException,
    PreconditionFailedException,
    NotAcceptableException,
    MethodNotAllowedException,
    UnauthorizedException,
    NotImplementedException,
    BadGatewayException,
    GatewayTimeoutException,
    ConflictException,
    GoneException,
    MisdirectedException,
    ImATeapotException,
    HttpException,
  ];
  return exceptions.some((exception) => error instanceof exception);
};
